
services:
  backend:
    image: node:20
    container_name: finance-tracker-backend
    command:
      - sh
      - -c
      - |
        npm install && npm run dev
    volumes:
      - ./backend:/app
    working_dir: /app
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
  frontend:
    image: node:20
    container_name: finance-tracker-frontend
    command:
      - sh
      - -c
      - |
        npm install && npm run dev
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    working_dir: /app
    environment:
      - API_TARGET=http://backend:3001
    ports:
      - "5173:5173"